const express = require("express");
const mongoose = require('mongoose');
const cookieSession = require('cookie-session');
const passport= require('passport');    // passport is to say use them to cookie
const keys = require('./config/keys');
const bodyParser = require('body-parser');


require('./models/User'); // model being created first and passport the second
require("./services/passport");
require('./models/Survey');




//connceting to the moongoose database 
mongoose.Promise = global.Promise;
mongoose.connect(keys.mongoURI, {useNewUrlParser:true});

const app = express();
app.use(bodyParser.json());

app.use(
    cookieSession({
        maxAge:30*24*60*60*1000,
        keys: [keys.cookieKey]
    })
);

app.use(passport.initialize());
app.use(passport.session());

require("./routes/authRoutes")(app); 
require("./routes/surveyRoutes")(app);
require('./routes/billingRoutes')(app);
// authRoute and billing Route export a function, so this require statement is turning into a function which we immediately call with the expressess app object


// valid 
// mathi ko second function lee, immediately invokes the function that is required in.

// for the production line NODE_ENV is automatically generated by heroku
if (process.env.NODE_ENV ==='production'){
    //Express will server up the production assets
    //Like our main.js or  main.css files
    app.use(express.static('client/build'));


    //Express will serve up index.html file 
    //if it does not recognoize the route
    const path = require('path');
    app.get ('*', (req,res)=>{
        res.sendFile(path.resolve(__dirname , 'client', 'build', 'index.html'));
    });

}

const PORT = process.env.PORT || 5000;
app.listen(PORT);
