const mongoose = require('mongoose');
const Mailer = require('../services/Mailer');
const surveyTemplate = require('../services/emailTemplates/surveyTemplates');
const requireLogin = require('../middlewares/requireLogin');
const requireCredits = require ('../middlewares/requireCredits');

const Survey = mongoose.model('surveys');


module.exports = app => {
    app.get('/api/surveys/thanks',(req,res)=>{
        res.send('Thanks you for voting');
    });

    app.post('/api/surveys', requireLogin, requireCredits, async(req,res)=>{
        const { title, subject, body, recipients }=req.body; 
        // access to differernt property

        //creating the instances of Survey in memory
        const survey= new Survey({
            title ,
            subject,
            body,   
            recipients: recipients.split(',').map(email=> ({
                email: email.trim()})), 
             _user: req.user.id,  //id is generated by mongoose
            dateSent:Date.now()
        });
        // ES6 title body:body => body only
          
            //Es6 . map (email=> ({ email }))   bracket for shortened object , if not js intrepreter will think as function
            //array of strings... for evey email add return object... with the property email that points out the user email

        //Great place to send email
        const mailer = new Mailer(survey,surveyTemplate(survey)); // 1st parameter is  object and 2nd parameter is html
        
        try{
        await mailer.send();
        await survey.save();
        req.user.credits -=1;
        const user = await  req.user.save(); // this is the user from now onwards
        
        
        res.send(user);
        } catch(err){
            res.status(422).send(err);        // something is wrong that you sent us
        }
    });
};



// Web hook: It is anything where some outside API is fascilitating some process and gives our application somekind of callback.(SANDHOOK)