const mongoose = require('mongoose');
const Mailer = require('../services/Mailer');
const surveyTemplate = require('../services/emailTemplates/surveyTemplates');

const Survey = mongoose.model('surveys');
module.exports = app => {
    app.post ('/api/surveys', (req,res)=>{
        const {title, subject, body, recipients}=req.body; 
        // access to differernt property

        //creating the instances of Survey in memory
        const survey= new Survey({
            title,
            subject:subject,
            body,    // ES6 title body:body => body only
            recipients: recipients.split(',').map(email =>({email: email.trim() })),
            //Es6 . map (email=> ({ email }))   bracket for shortened object , if not js intrepreter will think as function
            //array of strings... for evey email add return object... with the property email that points out the user email

            _user: req.user.id,  //id is generated by mongoose
            dateSent:Date.now()



        });

        //Great place to send email
        const mailer = new Mailer(survey,surveyTemplate(survey)); // 1st parameter is  object and 2nd parameter is html
        mailer.send();
    });
};



// Web hook: It is anything where some outside API is fascilitating some process and gives our application somekind of callback.(SANDHOOK)